# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "olegd/lxc-centos6-hadoop260-hive121"
  (1..2).each do |i|
    config.vm.define "box#{i}" do |node|
      node.vm.hostname = "box#{i}.lxc"
      node.vm.provider :lxc do |lxc|
        lxc.container_name = "box#{i}"
      end
    end
  end

end
