#!/bin/bash

if [ -n "$JAVA_HOME" ]; then
  RUNNER="${JAVA_HOME}/bin/java"
else
  RUNNER=java
fi

SCRIPT_HOME="$(cd `dirname $0`; pwd)"
JAR_NAME="hive-metastore-sync-0.0.1-SNAPSHOT.jar"
echo
exec $RUNNER -cp $CLASSPATH:$SCRIPT_HOME/target/$JAR_NAME:$SCRIPT_HOME/$JAR_NAME com.wandisco.hivesync.main.Main $*
